name: Aseprite Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Download Aseprite
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/aseprite'
          fileName: '*.zip'
          latest: true
          extract: true
      - uses: actions/checkout@v4
        with:
          shell: cmd
          run: |
            dir