name: Aseprite Builder v1.3.13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Download Aseprite v1.3.13
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/aseprite'
          fileName: '*.zip'
          tag: v1.3.13
          extract: true

      - name: Download Skia
        uses: robinraju/release-downloader@v1.12
        with:
            repository: 'aseprite/skia'
            fileName: 'Skia-Windows-Release-x64.zip'
            tag: m102-861e4743af

      - name: Extract Skia
        shell: pwsh
        run: | 
          Expand-Archive Skia-Windows-Release-x64.zip -DestinationPath skia
          Remove-Item -Path Skia-Windows-Release-x64.zip

      - name: List Dirs (debug)
        shell: cmd
        run: |
          dir

  build:
    runs-on: windows-latest
    steps:
        - name: build
          uses: seanmiddleditch/gha-setup-vsdevenv@v5