name: Aseprite Builder v1.3.13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Download Aseprite v1.3.13
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/aseprite'
          fileName: '*.zip'
          tag: v1.3.13
          extract: true

      - name: Download Skia
        uses: robinraju/release-downloader@v1.12
        with:
            repository: 'aseprite/skia'
            fileName: 'Skia-Windows-Release-x64.zip'
            tag: m102-861e4743af

      - name: Extract Skia
        shell: pwsh
        run: | 
          Expand-Archive Skia-Windows-Release-x64.zip -DestinationPath skia
          Remove-Item -Path Skia-Windows-Release-x64.zip

      - name: List Dirs (debug)
        shell: cmd
        run: |
          dir

  build:
    runs-on: windows-latest
    steps:
        - name: Setup Perl environment
          uses: shogo82148/actions-setup-perl@v1.33.0
        
        - name: Install LLVM and Clang
          uses: KyleMayes/install-llvm-action@v2.0.6
          with:
            version: 19.1.7
        - name: Setup Cmake and Ninja
          uses: lukka/get-cmake@latest
          with:
            cmakeVersion: latest
            ninjaVersion: latest
        - name: Install VS2022
          shell: pwsh
          run: |
            $user = New-Object System.Net.WebClient
            $user.DownloadFile(https://aka.ms/vs/17/release/vs_community.exe, vs2022.exe)
            $user.DownloadFile(https://raw.githubusercontent.com/pizzapi2012/AsepriteBuilderActions/refs/heads/main/aseprite.vsconfig, aseprite.vsconfig)
            Start-Process vs2022.exe -Verb runAs -ArgumentList ("--passive","--quiet","--norestart","--config aseprite.vsconfig") -Wait