name: Aseprite Builder v1.3.13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Download Aseprite v1.3.13
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/aseprite'
          fileName: '*.zip'
          tag: v1.3.13
          extract: true

      - name: Download Skia
        uses: robinraju/release-downloader@v1.12
        with:
            repository: 'aseprite/skia'
            fileName: 'Skia-Windows-Release-x64.zip'
            tag: m102-861e4743af

      - name: Extract Skia
        shell: pwsh
        run: | 
          Expand-Archive Skia-Windows-Release-x64.zip -DestinationPath skia
          Remove-Item -Path Skia-Windows-Release-x64.zip

      - name: List Dirs (debug)
        shell: cmd
        run: |
          dir

  build:
    runs-on: windows-latest
    steps:
        - name: build
          uses: johnnynunez/gha-setup-vsdevenv@v1
          with:
            arch: x64
            winsdk: 10.0.22621.0
            toolset_version: v143
            components: "Microsoft.VisualStudio.Component.CoreEditor;Microsoft.VisualStudio.Workload.CoreEditor;Microsoft.VisualStudio.Component.Roslyn.Compiler;Microsoft.Component.MSBuild;Microsoft.VisualStudio.Component.TextTemplating;Microsoft.VisualStudio.Component.VC.CoreIde;Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.Graphics.Tools;Microsoft.VisualStudio.Component.VC.DiagnosticTools;Microsoft.VisualStudio.Component.Windows11SDK.22621;Microsoft.VisualStudio.Component.VC.ATL,Microsoft.VisualStudio.Component.VC.Redist.14.Latest,Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core,Microsoft.VisualStudio.Component.Windows11Sdk.WindowsPerformanceToolkit,Microsoft.VisualStudio.Component.CppBuildInsights,Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake,Microsoft.VisualStudio.Component.VC.CMake.Project;Microsoft.VisualStudio.Component.Vcpkg,Microsoft.VisualStudio.Workload.NativeDesktop"
