name: Aseprite Builder v1.3.13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Download Aseprite v1.3.13
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/aseprite'
          fileName: '*.zip'
          tag: v1.3.13
          extract: true
      - name: Download Skia
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'aseprite/skia'
          fileName: 'Skia-Windows-Release-x64.zip'
          tag: m102-861e4743af
          extract: true
      - name: listdirs
        shell: cmd
        run: |
          dir